### ISSUE TITLE
some snippets are not working

### ISSUE THREAD

**Issue by RoduanKD** [rjrodriguez/RCH-Bootstrap-4-Snippets#3]
Hello ...
first I would like to thank you for this extension it is really fantastic.

my problem is when I start typing "bs4" the snippets list pops and for example I continue typing "bs4navbar" I will have 3 snippets to  choose from ("bs4navbar", "bs4navbar_basic", "bs4navbar_centered")
and then when I choose "bs4navbar_basic" the snippet doesn't work ! but when I choose the first one ("bs4navbar") it work perfectly with no problem 😄 .

I've tried to type "bs4navbar_basic" and the TAB what happens that it will converted to a tag like this :
<bs4navbar_basic></bs4navbar_basic>

(also tried to press ctrl + space and then choose it, but it didn't work )

thank you so much again for this great extension you made 😃 .

**Comment by rjrodriguez** [comment]
Thanks for your feedback, Roduan. You're right. I just uploaded an update to the scripts. Please try updating the extension, it should work. And let me know if you find another error or problem. Thanks again.

**Comment by RoduanKD** [comment]
Thank you so much it works perfectly now 😃
