### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by Elenchus15** [rjrodriguez/RCH-Bootstrap-4-Snippets#7]
Hello. I was wondering if you can help. I first installed it on Brackets the regular way, then when it didn't work, I installed it from your zipped file here. It is only giving me the buttons and nothing else. Not the carousel, not the cards.. nothing else. Can you help? 
I must say it is a great extension but I just wish it works. 
Thank you for your efforts. :)

**Comment by rjrodriguez** [comment]
Hi @Elenchus15 
Let me know: After installing the extension, enabling it, can you create the Bootstrap base HTML with the "bs4html" shortcut?
If you were able to do it, the next thing is to write the prefix "bs4" and a context menu will open. In it you will find the first shortcuts alphabetically and yes, they correspond to the buttons. If you keep typing some extra character, for example the letter "c" (for carousels), the shortcut list will show you the shortcuts alphabetically.
The context menu preview cannot list all shortcuts at once, so it is useful to gradually learn the names according to the documentation.
Let me know if you have any other issue.

**Comment by Elenchus15** [comment]
Excellent. Yes it worked. Thank you so much.  So I have to put in the bs4html template first always? It's not working on any other BS page. Only the buttons work on other BS pages.
Sorry - actually now, after creating the bs4html template, I can see the complete list on other pages as well. That is so strange. 
Thank you it's all working now. :)

**Comment by rjrodriguez** [comment]
> Excellent. Yes it worked. Thank you so much. So I have to put in the bs4html template first always? It's not working on any other BS page. Only the buttons work on other BS pages.

You can use it in any HTML file.
Glad to help you

**Comment by Elenchus15** [comment]
I hate to be a pain and you're so kind. The carousel has the images but they are stacked under each other in a row and it's not working. I tried it on the bs4html template and tried it on a regular BS page. Any ideas why?

**Comment by rjrodriguez** [comment]
Hi @Elenchus15 !
Sounds like a css or js issue. Please, verify if stylesheets and js scripts are properly linked... If so, could you provide the source code or a link to the HTML?

**Comment by Elenchus15** [comment]
Sorry for the late response. That might be the issue. I have to check and will let you know for sure. I thought it did it automatically so did not really check it. Apologies.
