### ISSUE TITLE
snippet not working in brackets

### ISSUE THREAD

**Issue by daman9999** [rjrodriguez/RCH-Bootstrap-4-Snippets#9]
when i write bs4 and press tab it produces nothing the option in brackets is also enabled from edit -> enable RCH Bootstrap snippet but works well with down key

**Comment by rjrodriguez** [comment]
Hi @daman9999. Have you tried the down arrow key?

**Comment by daman9999** [comment]
> Hi @daman9999. Have you tried the down arrow key?

Yes sir, i mentioned it works well with down key. I guess i have i
Other extensions installed alongside this extension thats why it is not working with tab key . Idk its a bug or something else i thought to inform you

**Comment by rjrodriguez** [comment]
Oh! I see! Thank you. I think I could be the Emmet extension that uses the tab key as a trigger too. I'm gonna change the description until I find the solution.
